FROM adoptopenjdk/openjdk11
EXPOSE 8080

# Set the name of the application's jar file
ARG JAR_FILE=journey-orchestrator-aggregator-all.jar
ENV JAR_FILE ${JAR_FILE}

# Set the path to the application's jar file - this is the artifact generated by maven as specified in the application's pom.xml
ARG JAR_PATH=build/libs/${JAR_FILE}

# Add the application's jar to the container
ADD ${JAR_PATH} ${JAR_FILE}

# Run the jar file
CMD java \
        -jar ${JAR_FILE}